version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 15672
      - 5672
  notification:
    build: .
    container_name: "notification"
    command: make run
    depends_on:
      - rabbitmq
    environment:
      LOGIN: "rabbitmq"
      PASS: "rabbitmq"
      LINK: rabbitmq
      PORT: 5672
    links:
      - rabbitmq
    volumes:
      - .:/app/
    expose:
      - 5228
      - 5229
      - 5230