version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - "5672:5672"
    expose:
      - 15672
      - 5672
  api:
    build: .
    container_name: "notification"
    command: make run
    depends_on:
      - rabbitmq
    environment:
      NAME: rabbitmq
    links:
      - rabbitmq
    volumes:
      - .:/app/
    expose:
      - 5228
      - 5229
      - 5230